id = "mojo-syntax"
name = "Mojo Syntax"
description = "Mojo syntax highlighting and language configuration for Zed."
version = "0.0.1"
schema_version = 1
authors = ["zed-mojo contributors"]
repository = "https://github.com/USBashka/zed-mojo-syntax"

[grammars.mojo]
repository = "https://github.com/USBashka/tree-sitter-mojo-zed"
commit = "0a10ea2bc42c602a5e965da3b0c2e36d36f4b720"
